name: Third-Party (jbig2enc + verapdf)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/third_party.yml"

jobs:
  # ========== Job 1: jbig2enc + Leptonica ==========
  jbig2enc:
    name: jbig2enc 0.30 (+leptonica) — ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-14, windows-latest ]

    steps:
      - name: Show commit
        run: echo "Commit: ${{ github.sha }}"

      # ---------- Linux ----------
      - name: Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential autoconf automake libtool pkg-config \
            leptonica-dev zlib1g-dev libpng-dev libjpeg-turbo8-dev libtiff-dev git
      - name: Build jbig2enc (Linux)
        if: runner.os == 'Linux'
        run: |
          set -eux
          git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
          cd jbig2enc
          ./autogen.sh
          ./configure --prefix="$PWD/../install_jb2"
          make -j
          make install
      - name: Collect artifacts (Linux)
        if: runner.os == 'Linux'
        run: |
          set -eux
          mkdir -p out/jbig2enc/{bin,lib,include}
          # 主可执行
          cp -v install_jb2/bin/jbig2enc out/jbig2enc/bin/ || true
          # 头文件（有些版本只安装可执行，没有库/头，这里兼容）
          if [ -d install_jb2/include ]; then cp -rv install_jb2/include/* out/jbig2enc/include/; fi
          # 共享库（如有）
          if ls install_jb2/lib/*.so* 1>/dev/null 2>&1; then cp -v install_jb2/lib/*.so* out/jbig2enc/lib/; fi
      - name: Upload (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-0.30-Linux-${{ github.sha }}
          path: out/**

      # ---------- macOS ----------
      - name: macOS deps
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install autoconf automake libtool pkg-config leptonica libpng jpeg-turbo libtiff git
      - name: Build jbig2enc (macOS)
        if: runner.os == 'macOS'
        run: |
          set -eux
          git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
          cd jbig2enc
          ./autogen.sh
          ./configure --prefix="$PWD/../install_jb2"
          make -j
          make install
      - name: Collect artifacts (macOS)
        if: runner.os == 'macOS'
        run: |
          set -eux
          mkdir -p out/jbig2enc/{bin,lib,include}
          cp -v install_jb2/bin/jbig2enc out/jbig2enc/bin/ || true
          if [ -d install_jb2/include ]; then cp -rv install_jb2/include/* out/jbig2enc/include/; fi
          if ls install_jb2/lib/*.dylib 1>/dev/null 2>&1; then cp -v install_jb2/lib/*.dylib out/jbig2enc/lib/; fi
      - name: Upload (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-0.30-macOS-${{ github.sha }}
          path: out/**

      # ---------- Windows (MSYS2 + MINGW64) ----------
      - name: Setup MSYS2 (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          msystem: MINGW64
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-leptonica
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff
      - name: Build jbig2enc (Windows, MSYS2 MINGW64)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          set -eux
          git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
          cd jbig2enc
          ./autogen.sh
          ./configure --prefix="$PWD/../install_jb2"
          make -j
          make install
      - name: Collect artifacts (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          set -eux
          mkdir -p out/jbig2enc/{bin,lib,include}
          # MSYS2 安装在 C:\msys64\mingw64，运行所需 DLL 位于 mingw64/bin
          cp -v install_jb2/bin/jbig2enc.exe out/jbig2enc/bin/ || true
          # 打包运行所需的 DLL（最常见是 leptonica 与图像编解码相关）
          cp -v /c/msys64/mingw64/bin/lept*.dll out/jbig2enc/bin/ || true
          cp -v /c/msys64/mingw64/bin/libpng*.dll out/jbig2enc/bin/ || true
          cp -v /c/msys64/mingw64/bin/libjpeg*.dll out/jbig2enc/bin/ || true
          cp -v /c/msys64/mingw64/bin/libtiff*.dll out/jbig2enc/bin/ || true
          cp -v /c/msys64/mingw64/bin/zlib*.dll out/jbig2enc/bin/ || true
          # 头文件/库（如有安装）
          if [ -d install_jb2/include ]; then cp -rv install_jb2/include/* out/jbig2enc/include/; fi
          if ls install_jb2/lib/*.a 1>/dev/null 2>&1; then cp -v install_jb2/lib/*.a out/jbig2enc/lib/; fi
      - name: Upload (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-0.30-Windows-${{ github.sha }}
          path: out/**

  # ========== Job 2: veraPDF（下载官方包即可） ==========
  verapdf:
    name: veraPDF 1.28.2 — ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-14, windows-latest ]
    steps:
      - name: Download veraPDF (zip + asc)
        shell: bash
        run: |
          set -eux
          mkdir out && cd out
          curl -fLO https://software.verapdf.org/rel/arlington/1.28/verapdf-arlington-1.28.2-installer.zip
          curl -fLO https://software.verapdf.org/rel/arlington/1.28/verapdf-arlington-1.28.2-installer.zip.asc
      - name: Upload veraPDF bundle
        uses: actions/upload-artifact@v4
        with:
          name: verapdf-1.28.2-${{ runner.os }}
          path: out/**
