name: Minimal CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/main.yml"

jobs:
  hello:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions"
