# .github/workflows/OpenCV_Linux_GPU.yml

name: Build Extended OpenCV (Linux GPU Only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENCV_VERSION: '4.12.0'
  INSTALL_DIR: ${{ github.workspace }}/install

jobs:
  build-gpu:
    name: Build GPU for Linux
    runs-on: ubuntu-latest
    container: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

    env:
      OPENCV_MODULES_LIST: "core,imgproc,imgcodecs,highgui,ml,quality,features2d,flann,ximgproc,calibd,photo,objdetect,text,dnn,phase_unwrapping,xfeatures2d,line_descriptor,bgsegm,img_hash,gapi,cudaarithm,cudabgsegm,cudacodec,cudafeatures2d,cudafilters,cudaimgproc,cudalegacy,cudawarping,cudev"

    steps:
      - name: Install container build dependencies
        shell: bash
        run: |
          export DEBIAN_FRONTEND=noninteractive
          # 【最终修正】安装官方的 CUDA 开发库元数据包，它会自动包含所有子库
          apt-get update && apt-get install -y --no-install-recommends \
            git cmake build-essential python3 python3-pip python3-numpy \
            libcudnn8-dev \
            cuda-libraries-dev-12-1 \
            libatlas-base-dev gfortran

      - name: Checkout OpenCV Source Code
        uses: actions/checkout@v4
        with:
          repository: opencv/opencv
          ref: ${{ env.OPENCV_VERSION }}
          # 【修正】删除 'path' 参数，让 action 使用默认路径 'opencv'

      - name: Checkout OpenCV Contrib Source Code
        uses: actions/checkout@v4
        with:
          repository: opencv/opencv_contrib
          ref: ${{ env.OPENCV_VERSION }}
          # 【修正】删除 'path' 参数，让 action 使用默认路径 'opencv_contrib'

      - name: Configure CMake (Linux with CUDA)
        # 【修正】工作目录现在是 'opencv'，因为这是 checkout 的默认结果
        working-directory: opencv
        shell: bash
        run: |
          # 【修正】所有路径都使用绝对路径，确保万无一失
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DOPENCV_EXTRA_MODULES_PATH=${{ github.workspace }}/opencv_contrib/modules \
            -DBUILD_LIST="${{ env.OPENCV_MODULES_LIST }}" \
            -DWITH_CUDA=ON \
            -DWITH_CUDNN=ON \
            -DOPENCV_DNN_CUDA=ON \
            -DCUDA_ARCH_BIN="7.5 8.0 8.6" \
            -DBUILD_ZLIB=OFF -DBUILD_PNG=OFF -DBUILD_JPEG=OFF -DBUILD_TIFF=OFF -DBUILD_WEBP=OFF \
            -DBUILD_SHARED_LIBS=ON -DBUILD_opencv_world=ON \
            -DWITH_IPP=OFF -DWITH_TBB=OFF -DWITH_OPENMP=OFF -DWITH_QT=OFF -DWITH_FFMPEG=OFF \
            -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF \
            -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }}

      - name: Build and Install OpenCV
        working-directory: opencv
        shell: bash
        run: cmake --build build --config Release --target install -j4

      - name: Upload OpenCV Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opencv-world-gpu-linux
          path: ${{ env.INSTALL_DIR }}
          retention-days: 7
