# .github/workflows/OpenCV_Linux_GPU_Final.yml

name: Build Extended OpenCV (Linux GPU Only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENCV_VERSION: '4.12.0'
  # Remove the workspace-relative path for now
  # INSTALL_DIR: ${{ github.workspace }}/install

jobs:
  build-gpu:
    name: Build GPU for Linux
    runs-on: ubuntu-latest
    container: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

    env:
      OPENCV_MODULES_LIST: "core,imgproc,imgcodecs,highgui,ml,quality,features2d,flann,ximgproc,calib3d,photo,objdetect,text,dnn,phase_unwrapping,xfeatures2d,line_descriptor,bgsegm,img_hash,gapi,cudaarithm,cudabgsegm,cudacodec,cudafeatures2d,cudafilters,cudaimgproc,cudalegacy,cudawarping,cudev"

    steps:
      - name: Install basic build dependencies
        shell: bash
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update && apt-get install -y --no-install-recommends \
            git cmake build-essential python3 python3-pip python3-numpy \
            libatlas-base-dev gfortran

      - name: Clone OpenCV and Contrib repositories
        shell: bash
        run: |
          set -e
          echo "Cloning OpenCV repository..."
          git clone --depth 1 --branch ${{ env.OPENCV_VERSION }} https://github.com/opencv/opencv.git
          
          echo "Cloning OpenCV Contrib repository..."
          git clone --depth 1 --branch ${{ env.OPENCV_VERSION }} https://github.com/opencv/opencv_contrib.git

      - name: Configure CMake (Linux with CUDA)
        shell: bash
        run: |
          # Store the absolute path of the install directory
          export INSTALL_DIR_ABS=$(pwd)/install
          echo "Install directory will be: $INSTALL_DIR_ABS"
          
          # Create the install directory
          mkdir -p "$INSTALL_DIR_ABS"
          
          # Enter opencv directory
          cd opencv

          # Verify opencv_contrib modules
          echo "--- Verifying contents of opencv_contrib/modules ---"
          ls -la ../opencv_contrib/modules | head -20
          echo "--- Verification End ---"

          # Configure with absolute path
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DOPENCV_EXTRA_MODULES_PATH="../opencv_contrib/modules" \
            -DBUILD_LIST="${{ env.OPENCV_MODULES_LIST }}" \
            -DWITH_CUDA=ON \
            -DWITH_CUDNN=ON \
            -DOPENCV_DNN_CUDA=ON \
            -DCUDA_ARCH_BIN="7.5 8.0 8.6" \
            -DBUILD_ZLIB=OFF -DBUILD_PNG=OFF -DBUILD_JPEG=OFF -DBUILD_TIFF=OFF -DBUILD_WEBP=OFF \
            -DBUILD_SHARED_LIBS=ON -DBUILD_opencv_world=ON \
            -DWITH_IPP=OFF -DWITH_TBB=OFF -DWITH_OPENMP=OFF -DWITH_QT=OFF -DWITH_FFMPEG=OFF \
            -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF \
            -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR_ABS"

      - name: Build and Install OpenCV
        shell: bash
        run: |
          cd opencv
          # Build
          cmake --build build --config Release -j4
          # Explicitly run install
          cmake --build build --config Release --target install

      - name: Verify installation
        shell: bash
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Checking install directory ==="
          if [ -d "install" ]; then
            echo "Install directory exists"
            echo "Contents of install/:"
            ls -la install/
            echo "Contents of install/lib (if exists):"
            ls -la install/lib/ 2>/dev/null || echo "No lib directory"
            echo "Finding all .so files:"
            find install -name "*.so*" -type f
          else
            echo "Install directory not found at $(pwd)/install"
            echo "Searching for install directories:"
            find . -name "install" -type d
          fi
          
          echo "=== Finding OpenCV libraries anywhere ==="
          find . -name "libopencv*.so*" -type f | head -20

      - name: Create artifact archive
        shell: bash
        run: |
          # If the install directory exists, create a tar archive
          if [ -d "install" ]; then
            echo "Creating archive from install directory"
            tar czf opencv-gpu-linux.tar.gz -C install .
            ls -lh opencv-gpu-linux.tar.gz
          else
            echo "ERROR: Install directory not found!"
            exit 1
          fi

      - name: Upload OpenCV Artifacts (Archive)
        uses: actions/upload-artifact@v4
        with:
          name: opencv-world-gpu-linux-archive
          path: opencv-gpu-linux.tar.gz
          retention-days: 7

      - name: Upload OpenCV Artifacts (Directory)
        uses: actions/upload-artifact@v4
        with:
          name: opencv-world-gpu-linux
          path: install
          retention-days: 7
          if-no-files-found: warn
