# .github/workflows/OpenCV.yml

name: Build Minimal OpenCV with vcpkg (No JSON)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_PACKAGES_COMMAND: "opencv4[core,imgproc,calib3d,world]"
  VCPKG_PACKAGES_KEY: "opencv4-core-imgproc-calib3d-world"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: macos-latest
            triplet: x64-osx
          - os: ubuntu-latest
            triplet: x64-linux

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_ROOT }}
          key: vcpkg-${{ matrix.os }}-${{ env.VCPKG_PACKAGES_KEY }}
          restore-keys: |
            vcpkg-${{ matrix.os }}-

      # --- 关键修正：为不同平台使用不同的引导脚本 ---
      
      # 为 Linux 和 macOS (Unix-like) 系统执行的步骤
      - name: Bootstrap vcpkg (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [ ! -d "${{ env.VCPKG_ROOT }}" ]; then
            git clone https://github.com/microsoft/vcpkg.git "${{ env.VCPKG_ROOT }}"
          fi
          cd "${{ env.VCPKG_ROOT }}"
          ./bootstrap-vcpkg.sh

      # 为 Windows 系统执行的步骤
      - name: Bootstrap vcpkg (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if (-not (Test-Path "${{ env.VCPKG_ROOT }}")) {
            git clone https://github.com/microsoft/vcpkg.git "${{ env.VCPKG_ROOT }}"
          }
          cd "${{ env.VCPKG_ROOT }}"
          ./bootstrap-vcpkg.bat

      # ---------------------------------------------------

      - name: Install OpenCV using vcpkg (Classic Mode)
        shell: bash # vcpkg 命令在所有平台都能被 bash 正确调用
        run: |
          ${{ env.VCPKG_ROOT }}/vcpkg install ${{ env.VCPKG_PACKAGES_COMMAND }} --triplet ${{ matrix.triplet }}

      - name: Upload OpenCV Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opencv-minimal-${{ matrix.os }}
          path: ${{ env.VCPKG_ROOT }}/installed/${{ matrix.triplet }}
          retention-days: 7
