# .github/workflows/OpenCV_Linux_GPU.yml
name: Build Extended OpenCV (Linux GPU Only)

on:
  push:
    branches: [ main ]
    paths:
      # 只有这些路径变化时才会触发
      - '.github/workflows/OpenCV_Linux_GPU.yml'   # 修改本 yml 也触发
      - 'ci/opencv/**'
      - 'scripts/opencv/**'
      - 'CMakeLists.txt'
      - 'opencv/**'
      - 'opencv_contrib/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenCV_Linux_GPU.yml'
      - 'ci/opencv/**'
      - 'scripts/opencv/**'
      - 'CMakeLists.txt'
      - 'opencv/**'
      - 'opencv_contrib/**'
  workflow_dispatch:   # 仍然允许手动触发

# 同一 workflow + 分支上有新提交时，自动取消旧 run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# 最小权限原则（可选但推荐）
permissions:
  contents: read

env:
  OPENCV_VERSION: '4.12.0'
  INSTALL_DIR: ${{ github.workspace }}/install

jobs:
  build-gpu:
    name: Build GPU for Linux
    runs-on: ubuntu-latest
    container: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

    env:
      OPENCV_MODULES_LIST: "core,imgproc,imgcodecs,highgui,ml,quality,features2d,flann,ximgproc,calib3d,photo,objdetect,text,dnn,phase_unwrapping,xfeatures2d,line_descriptor,bgsegm,img_hash,gapi,cudaarithm,cudabgsegm,cudacodec,cudafeatures2d,cudafilters,cudaimgproc,cudalegacy,cudawarping,cudev"

    steps:
      - name: Install container build dependencies
        shell: bash
        run: |
          set -euo pipefail
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          # 这些工具用于构建，cuDNN 已在镜像中；cublas 随 CUDA 工具包提供，无需额外安装
          apt-get install -y --no-install-recommends \
            git cmake build-essential python3 python3-pip python3-numpy \
            libatlas-base-dev gfortran
          pip3 install --no-cache-dir numpy

      - name: Checkout OpenCV Source Code
        uses: actions/checkout@v4
        with:
          repository: opencv/opencv
          ref: ${{ env.OPENCV_VERSION }}
          path: opencv

      - name: Checkout OpenCV Contrib Source Code
        uses: actions/checkout@v4
        with:
          repository: opencv/opencv_contrib
          ref: ${{ env.OPENCV_VERSION }}
          path: opencv_contrib

      - name: Configure CMake (Linux with CUDA)
        working-directory: ./opencv
        shell: bash
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DOPENCV_EXTRA_MODULES_PATH="${{ github.workspace }}/opencv_contrib/modules" \
            -DBUILD_LIST="${{ env.OPENCV_MODULES_LIST }}" \
            -DWITH_CUDA=ON \
            -DWITH_CUDNN=ON \
            -DOPENCV_DNN_CUDA=ON \
            -DCUDA_ARCH_BIN="7.5 8.0 8.6" \
            -DBUILD_ZLIB=OFF -DBUILD_PNG=OFF -DBUILD_JPEG=OFF -DBUILD_TIFF=OFF -DBUILD_WEBP=OFF \
            -DBUILD_SHARED_LIBS=ON -DBUILD_opencv_world=ON \
            -DWITH_IPP=OFF -DWITH_TBB=OFF -DWITH_OPENMP=OFF -DWITH_QT=OFF -DWITH_FFMPEG=OFF \
            -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF \
            -DCMAKE_INSTALL_PREFIX="${{ env.INSTALL_DIR }}"

      - name: Build and Install OpenCV
        working-directory: ./opencv
        shell: bash
        run: cmake --build build --config Release --target install -j4

      - name: Upload OpenCV Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opencv-world-gpu-linux
          path: ${{ env.INSTALL_DIR }}
          retention-days: 7
