name: jbig2enc (Windows only)

on:
  workflow_dispatch:  # manual only

jobs:
  jbig2enc_windows:
    name: jbig2enc 0.30 — Windows (MSYS2/MINGW64)
    runs-on: windows-latest

    steps:
      - name: Setup MSYS2 (MINGW64) and dependencies
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          msystem: MINGW64
          install: >-
            base-devel
            autoconf
            automake
            libtool
            m4
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff
            mingw-w64-x86_64-leptonica

      - name: Verify pkg-config entries (zlib/leptonica)
        shell: msys2 {0}
        run: |
          set -eux
          ls -l /mingw64/lib/pkgconfig || true
          ls -l /mingw64/lib/pkgconfig/zlib.pc
          ls -l /mingw64/lib/pkgconfig/lept.pc
          pkgconf --modversion zlib
          pkgconf --modversion lept
          pkgconf --cflags zlib || true
          pkgconf --libs zlib || true

      - name: Build jbig2enc 0.30 (autotools / MSYS2)
        shell: msys2 {0}
        run: |
          set -eux
          # 安全拼接 PKG_CONFIG_PATH（避免未定义变量导致 -u 退出）
          export PKG_CONFIG_PATH="/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"

          # 从 pkgconf 读取 zlib 的 CFLAGS/LIBS；若失败则兜底为标准目录
          ZCFLAGS="$(pkgconf --cflags zlib || true)";  [ -n "$ZCFLAGS" ] || ZCFLAGS="-I/mingw64/include"
          ZLIBS="$(pkgconf --libs zlib   || true)";    [ -n "$ZLIBS" ]   || ZLIBS="-L/mingw64/lib -lz"

          export CPPFLAGS="${ZCFLAGS} ${CPPFLAGS:-}"
          export LDFLAGS="${ZLIBS} ${LDFLAGS:-}"

          git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
          cd jbig2enc
          ./autogen.sh

          # 传入显示的 zlib 变量（双保险），避免 configure 误判
          ZLIB_CFLAGS="$ZCFLAGS" ZLIB_LIBS="$ZLIBS" \
          ./configure --prefix="$PWD/../install_jb2"

          make -j
          make install

      - name: Collect and upload artifact
        shell: bash
        run: |
          set -eux
          mkdir -p out/bin out/lib out/include
          # 主程序
          cp -v install_jb2/bin/jbig2enc.exe out/bin/
          # 常见运行期 DLL（放同目录，减少 PATH 依赖）
          cp -v /c/msys64/mingw64/bin/lept*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/libpng*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/libjpeg*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/libtiff*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/zlib*.dll out/bin/ || true
          # 开发文件（如生成）
          if [ -d install_jb2/include ]; then cp -rv install_jb2/include/* out/include/; fi
          if ls install_jb2/lib/* 1>/dev/null 2>&1; then cp -v install_jb2/lib/* out/lib/; fi
        # 上传
      - uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-0.30-Windows
          path: out/**
