  - name: Build jbig2enc 0.30 (autotools / MSYS2, force zlib)
    shell: msys2 {0}
    run: |
      set -eux

      # 用我们自己装的 zlib 前缀（上一步 install_zlib）
      export ZCFLAGS="-I$PWD/install_zlib/include"
      # 关键：在 zlib 的链接参数里显式加入 -lws2_32（Windows 上少数探测需要）
      export ZLIBS="-L$PWD/install_zlib/lib -lz -lws2_32"

      # 叠加到通用标志（双保险）
      export CPPFLAGS="${ZCFLAGS} ${CPPFLAGS:-}"
      export LDFLAGS="${ZLIBS} ${LDFLAGS:-}"
      export LIBS="${ZLIBS} ${LIBS:-}"

      git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
      cd jbig2enc
      ./autogen.sh

      # 再加一层保险：用 Autoconf cache 强制命中 zlib 探测
      ac_cv_header_zlib_h=yes ac_cv_lib_z_deflate=yes \
      ZLIB_CFLAGS="$ZCFLAGS" ZLIB_LIBS="$ZLIBS" \
      ./configure ZLIB_CFLAGS="$ZCFLAGS" ZLIB_LIBS="$ZLIBS" \
                 --prefix="$PWD/../install_jb2" || { echo "=== configure failed, dumping tail of config.log ==="; tail -n 200 config.log; exit 1; }

      make -j
      make install
