  - name: Build jbig2enc 0.30 (autotools / MSYS2)
    shell: msys2 {0}
    run: |
      set -ex
      # 指向我们上一步安装的 zlib 前缀
      ZPREFIX="$PWD/install_zlib"

      # 关键：把 -lz 换成 “绝对路径的导入库” + 需要的 winsock
      export ZCFLAGS="-I$ZPREFIX/include"
      export ZLIBS="$ZPREFIX/lib/libz.dll.a -lws2_32"

      # 通用标志（双保险）
      export CPPFLAGS="$ZCFLAGS ${CPPFLAGS-}"
      export LDFLAGS="$ZLIBS ${LDFLAGS-}"
      export LIBS="$ZLIBS ${LIBS-}"

      git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
      cd jbig2enc
      ./autogen.sh

      # 强制告诉 autoconf：头文件与链接都 OK
      export ac_cv_header_zlib_h=yes
      export ac_cv_lib_z_deflate=yes
      export ZLIB_CFLAGS="$ZCFLAGS"
      export ZLIB_LIBS="$ZLIBS"

      ./configure --prefix="$PWD/../install_jb2" \
      || { echo "=== tail config.log ==="; tail -n 200 config.log || true; exit 1; }

      make -j
      make install
