name: jbig2enc (Windows only)

on:
  workflow_dispatch:  # manual only

jobs:
  jbig2enc_windows:
    name: jbig2enc 0.30 — Windows (MSYS2/MINGW64)
    runs-on: windows-latest

    steps:
      - name: Setup MSYS2 (MINGW64) and dependencies
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          msystem: MINGW64
          install: >-
            base-devel
            autoconf
            automake
            libtool
            m4
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff
            mingw-w64-x86_64-leptonica

      - name: Build jbig2enc 0.30 (autotools / MSYS2)
        shell: msys2 {0}
        run: |
          set -eux

          # pkg-config 搜索路径
          export PKG_CONFIG_PATH="/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"

          # 统一且稳妥的 zlib 编译/链接参数（无论 pkgconf 返回什么，都确保含 -L 与 -lz）
          ZCFLAGS="$(pkgconf --cflags zlib || true)";  [ -n "$ZCFLAGS" ] || ZCFLAGS="-I/mingw64/include"
          ZLIBS="$(pkgconf --libs zlib   || true)"
          # 强制补上库目录与 -lz（避免只有 -lz 导致找不到库）
          case " $ZLIBS " in
            *" -L/mingw64/lib "*) : ;;
            *) ZLIBS="-L/mingw64/lib ${ZLIBS}";;
          esac
          case " $ZLIBS " in
            *" -lz "*) : ;;
            *) ZLIBS="${ZLIBS} -lz";;
          esac

          # 叠加到通用标志（双保险）
          export CPPFLAGS="${ZCFLAGS} ${CPPFLAGS:-}"
          export LDFLAGS="${ZLIBS} ${LDFLAGS:-}"
          export LIBS="${ZLIBS} ${LIBS:-}"

          git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
          cd jbig2enc
          ./autogen.sh

          # 关键：同时以“环境前缀 + 显式参数”的方式传入 ZLIB_*
          ZLIB_CFLAGS="$ZCFLAGS" ZLIB_LIBS="$ZLIBS" \
          ./configure ZLIB_CFLAGS="$ZCFLAGS" ZLIB_LIBS="$ZLIBS" \
                     --prefix="$PWD/../install_jb2"

          make -j
          make install

      - name: Collect and upload artifact
        shell: bash
        run: |
          set -eux
          mkdir -p out/bin out/lib out/include
          # 主程序
          cp -v install_jb2/bin/jbig2enc.exe out/bin/
          # 常见运行期 DLL（放同目录，减少 PATH 依赖）
          cp -v /c/msys64/mingw64/bin/lept*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/libpng*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/libjpeg*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/libtiff*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/zlib*.dll out/bin/ || true
          # 开发文件（如生成）
          if [ -d install_jb2/include ]; then cp -rv install_jb2/include/* out/include/; fi
          if ls install_jb2/lib/* 1>/dev/null 2>&1; then cp -v install_jb2/lib/* out/lib/; fi
        # 上传
      - uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-0.30-Windows
          path: out/**
