name: Third-Party (jbig2enc only)
on:
  workflow_dispatch:   # ✅ 仅手动触发

jobs:
  # ---------------------- jbig2enc (+ leptonica) on macOS ----------------------
  jbig2enc_macos:
    name: jbig2enc 0.30 — macOS
    runs-on: macos-14
    steps:
      - name: Install build deps (Homebrew)
        run: |
          brew update
          # autotools & toolchain
          brew install autoconf automake libtool pkg-config git
          # image codecs for leptonica
          brew install libpng jpeg-turbo libtiff zlib
      - name: Build Leptonica (from source)
        run: |
          set -eux
          git clone --depth 1 https://github.com/DanBloomberg/leptonica.git
          cd leptonica
          ./autogen.sh
          ./configure --prefix="$PWD/../install_lept"
          make -j
          make install
      - name: Build jbig2enc 0.30 (autotools)
        run: |
          set -eux
          # 指向我们刚安装的 leptonica 前缀，避免 "Leptonica not detected"
          export PKG_CONFIG_PATH="$PWD/install_lept/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
          export CPPFLAGS="-I$PWD/install_lept/include ${CPPFLAGS:-}"
          export LDFLAGS="-L$PWD/install_lept/lib ${LDFLAGS:-}"
          git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
          cd jbig2enc
          ./autogen.sh
          ./configure --prefix="$PWD/../install_jb2"
          make -j
          make install
      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-0.30-macOS
          path: install_jb2/**

  # ---------------------- jbig2enc (+ leptonica) on Windows --------------------
  jbig2enc_windows:
    name: jbig2enc 0.30 — Windows (MSYS2/MINGW64)
    runs-on: windows-latest
    steps:
      - name: Setup MSYS2 (MINGW64) + deps
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          msystem: MINGW64
          install: >-
            # 工具链 & autotools（解决 aclocal/autoconf/libtool 缺失）
            base-devel
            autoconf
            automake
            libtool
            git
            # pkg-config (mingw 版)
            mingw-w64-x86_64-pkgconf
            # Leptonica 编译所需编解码库（mingw 版，放到 /mingw64）
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff
            mingw-w64-x86_64-zlib
            # 可选：优化构建稳定性
            m4
      - name: Build Leptonica (from source / MSYS2)
        shell: msys2 {0}
        run: |
          set -eux
          git clone --depth 1 https://github.com/DanBloomberg/leptonica.git
          cd leptonica
          ./autogen.sh
          ./configure --prefix="$PWD/../install_lept"
          make -j
          make install
      - name: Build jbig2enc 0.30 (autotools / MSYS2)
        shell: msys2 {0}
        run: |
          set -eux
          # 指向我们刚安装的 leptonica 前缀，避免检测失败
          export PKG_CONFIG_PATH="$PWD/install_lept/lib/pkgconfig:${PKG_CONFIG_PATH}"
          export CPPFLAGS="-I$PWD/install_lept/include ${CPPFLAGS}"
          export LDFLAGS="-L$PWD/install_lept/lib ${LDFLAGS}"
          git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
          cd jbig2enc
          ./autogen.sh
          ./configure --prefix="$PWD/../install_jb2"
          make -j
          make install
      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-0.30-Windows
          path: install_jb2/**
