name: jbig2enc Windows (with Leptonica)

on:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Setup MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            git
            m4
            autoconf
            automake
            libtool
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-leptonica
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff

      - name: Build jbig2enc 0.30
        shell: msys2 {0}
        run: |
          set -ex
          export PKG_CONFIG_PATH="/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig"
          git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
          cd jbig2enc
          ./autogen.sh
          ./configure --prefix="$PWD/../install_jb2"
          make -j$(nproc || echo 2)
          make install

      - name: Collect artifacts
        shell: msys2 {0}
        run: |
          set -ex
          mkdir -p out/bin out/include out/lib out/deps/leptonica out/logs

          # main exe
          cp -v install_jb2/bin/jbig2enc.exe out/bin/

          # runtime DLLs (存在才复制)
          for f in \
            /mingw64/bin/zlib1.dll \
            /mingw64/bin/lept*.dll \
            /mingw64/bin/libpng*.dll \
            /mingw64/bin/libjpeg*.dll \
            /mingw64/bin/libtiff*.dll \
            /mingw64/bin/libgcc_s_seh-1.dll \
            /mingw64/bin/libstdc++-6.dll \
            /mingw64/bin/libwinpthread-1.dll ; do
            [ -f "$f" ] && cp -v "$f" out/bin/ || true
          done

          # headers/libs for offline dev
          cp -rv /mingw64/include/leptonica out/deps/leptonica/include || true
          mkdir -p out/deps/leptonica/lib/pkgconfig
          cp -rv /mingw64/lib/libLept*.a out/deps/leptonica/lib || true
          cp -v /mingw64/lib/pkgconfig/lept*.pc out/deps/leptonica/lib/pkgconfig || true

          # jbig2enc install payloads (if any)
          [ -d install_jb2/include ] && cp -rv install_jb2/include/* out/include/ || true
          [ -d install_jb2/lib ] && cp -rv install_jb2/lib/* out/lib/ || true

          # logs
          [ -f jbig2enc/config.log ] && cp -v jbig2enc/config.log out/logs/config.log || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-0.30-windows-x86_64
          path: out/**
