name: jbig2enc Windows (x86_64)

on:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Setup MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            git
            m4
            autoconf
            automake
            libtool
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-leptonica
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff

      - name: Build jbig2enc 0.30
        shell: msys2 {0}
        run: |
          set -ex

          # 保证 /mingw64/bin 在 PATH 前面
          export PATH="/mingw64/bin:$PATH"

          # 1) 放一个 pkg-config 包装器，强制转发到 mingw 版 pkgconf
          WRAPBIN="$(mktemp -d)"
          printf '#!/bin/sh\nexec /mingw64/bin/pkgconf "$@"\n' > "$WRAPBIN/pkg-config"
          chmod +x "$WRAPBIN/pkg-config"
          export PATH="$WRAPBIN:$PATH"

          # 2) 诊断：两套命令都要能找到 zlib
          which pkg-config
          pkg-config --version
          pkg-config --modversion zlib

          which pkgconf
          pkgconf --version
          pkgconf --modversion zlib

          # 3) 试编译+链接（确保 -lz 可用）
          printf '#include <zlib.h>\nint main(){return (int)zlibVersion()[0];}\n' > ztest.c
          gcc -I/mingw64/include ztest.c -L/mingw64/lib -lz -o ztest.exe
          ./ztest.exe || true

          # 4) 拉源码并构建
          git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
          cd jbig2enc
          ./autogen.sh

          # 显式传入 zlib 标志（双保险）
          ./configure \
            --prefix="$PWD/../install_jb2" \
            ZLIB_CFLAGS="-I/mingw64/include" \
            ZLIB_LIBS="-L/mingw64/lib -lz"

          make -j$(nproc || echo 2)
          make install

      - name: Collect artifacts
        shell: msys2 {0}
        run: |
          set -ex
          mkdir -p out/bin out/include out/lib out/deps/leptonica out/logs

          # 主程序
          cp -v install_jb2/bin/jbig2enc.exe out/bin/

          # 常见运行时 DLL（存在就复制）
          for f in \
            /mingw64/bin/zlib1.dll \
            /mingw64/bin/lept*.dll \
            /mingw64/bin/libpng*.dll \
            /mingw64/bin/libjpeg*.dll \
            /mingw64/bin/libtiff*.dll \
            /mingw64/bin/libgcc_s_seh-1.dll \
            /mingw64/bin/libstdc++-6.dll \
            /mingw64/bin/libwinpthread-1.dll ; do
            [ -f "$f" ] && cp -v "$f" out/bin/ || true
          done

          # leptonica 头文件/库/pc，便于离线链接
          cp -rv /mingw64/include/leptonica out/deps/leptonica/include || true
          mkdir -p out/deps/leptonica/lib/pkgconfig
          cp -rv /mingw64/lib/libLept*.a out/deps/leptonica/lib || true
          cp -v  /mingw64/lib/pkgconfig/lept*.pc out/deps/leptonica/lib/pkgconfig || true

          # jbig2enc 安装产物（若有）
          [ -d install_jb2/include ] && cp -rv install_jb2/include/* out/include/ || true
          [ -d install_jb2/lib ]     && cp -rv install_jb2/lib/*     out/lib/     || true

          # 日志
          [ -f jbig2enc/config.log ] && cp -v jbig2enc/config.log out/logs/config.log || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-0.30-windows-x86_64
          path: out/**
