#
# GitHub Actions 工作流程：在 Windows (MinGW) 环境下构建 jbig2enc
#
# 摘要:
# 本文件根据用户提供的详细分析进行构建。
# 最终解决方案：放弃所有对脚本的补丁操作，采用更优雅、更标准的 Autotools 缓存机制。
# 通过在 configure 阶段直接注入 ac_cv_lib_ws2_32__head_libws2_32_a=yes，
# 从根源上解决了 jbig2enc 在 MinGW 上因 ws2_32 库检测瑕疵而导致的连锁失败问题。
#
name: Build jbig2enc on Windows

on:
  # 允许手动触发
  workflow_dispatch:
  # 在 push 到 main 分支时自动触发
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: 1. 检出代码
        uses: actions/checkout@v4

      - name: 2. 安装 MSYS2 及依赖包
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            autoconf
            automake
            libtool
            m4
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-leptonica
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff

      - name: 3. 克隆并准备 jbig2enc 源码
        run: |
          echo "克隆 jbig2enc 仓库..."
          git clone https://github.com/agl/jbig2enc.git
          cd jbig2enc
          
          echo "切换到 0.30 版本..."
          git checkout 0.30

      - name: 4. 生成 configure 脚本
        working-directory: ./jbig2enc
        run: |
          echo "正在运行 autogen.sh..."
          ./autogen.sh

      - name: 5. 配置、编译和安装
        working-directory: ./jbig2enc
        run: |
          # 创建一个独立的安装目录
          INSTALL_PREFIX="$(pwd)/build_output"
          mkdir -p "$INSTALL_PREFIX"

          echo "运行 ./configure 并注入缓存变量以修复 zlib 检测..."
          # 核心修正：直接向 configure 注入 ac_cv_lib_ws2_32__head_libws2_32_a=yes
          # 这直接解决了 jbig2enc 在 MinGW 上对 ws2_32 库的错误检测问题，
          # 从而避免了连锁触发的“zlib not detected”错误。这比打补丁更干净。
          ./configure \
            --prefix="$INSTALL_PREFIX" \
            ac_cv_lib_ws2_32__head_libws2_32_a=yes \
            ZLIB_CFLAGS="$(pkg-config --cflags zlib)" \
            ZLIB_LIBS="$(pkg-config --libs zlib)" \
            LEPTONICA_CFLAGS="$(pkg-config --cflags lept)" \
            LEPTONICA_LIBS="$(pkg-config --libs lept)"

          echo "运行 make..."
          make

          echo "运行 make install..."
          make install

      - name: 6. 收集并打包产物
        run: |
          # 用于存放最终产物的目录
          ARTIFACT_DIR="jbig2enc-release"
          mkdir -p "$ARTIFACT_DIR"

          INSTALL_BIN_DIR="jbig2enc/build_output/bin"
          MINGW_BIN_DIR="/mingw64/bin"

          echo "正在收集 jbig2enc.exe..."
          cp "$INSTALL_BIN_DIR/jbig2enc.exe" "$ARTIFACT_DIR/"

          echo "正在收集运行时依赖的 DLL 文件..."
          # 使用通配符来匹配 DLL，使其对库的版本变化更具鲁棒性
          cp "$MINGW_BIN_DIR/zlib1.dll" "$ARTIFACT_DIR/"
          cp "$MINGW_BIN_DIR/liblept*.dll" "$ARTIFACT_DIR/"
          cp "$MINGW_BIN_DIR/libpng*.dll" "$ARTIFACT_DIR/"
          cp "$MINGW_BIN_DIR/libjpeg*.dll" "$ARTIFACT_DIR/"
          cp "$MINGW_BIN_DIR/libtiff*.dll" "$ARTIFACT_DIR/"
          # 复制 GCC 运行时库
          cp "$MINGW_BIN_DIR/libstdc++-6.dll" "$ARTIFACT_DIR/"
          cp "$MINGW_BIN_DIR/libgcc_s_seh-1.dll" "$ARTIFACT_DIR/"
          cp "$MINGW_BIN_DIR/libwinpthread-1.dll" "$ARTIFACT_DIR/"

          echo "正在收集 config.log 以便调试..."
          cp "jbig2enc/config.log" "$ARTIFACT_DIR/"

          echo "打包目录内容一览:"
          ls -l "$ARTIFACT_DIR"

      - name: 7. 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-windows-x64
          path: jbig2enc-release/
