name: jbig2enc (Windows only)

on:
  workflow_dispatch:  # manual only

jobs:
  jbig2enc_windows:
    name: jbig2enc 0.30 — Windows (MSYS2/MINGW64)
    runs-on: windows-latest

    steps:
      - name: Setup MSYS2 (MINGW64) and dependencies
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          msystem: MINGW64
          install: >-
            base-devel
            autoconf
            automake
            libtool
            m4
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-leptonica
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff
            mingw-w64-x86_64-zlib

      - name: Build jbig2enc 0.30 (autotools / MSYS2)
        shell: msys2 {0}
        run: |
          set -eux
          # Let pkg-config find leptonica and codec deps installed in /mingw64
          export PKG_CONFIG_PATH="/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
          export CPPFLAGS="-I/mingw64/include ${CPPFLAGS:-}"
          export LDFLAGS="-L/mingw64/lib ${LDFLAGS:-}"

          git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
          cd jbig2enc
          ./autogen.sh
          ./configure --prefix="$PWD/../install_jb2"
          make -j
          make install

      - name: Collect and upload artifact
        shell: bash
        run: |
          set -eux
          mkdir -p out/bin out/lib out/include
          # Main executable
          cp -v install_jb2/bin/jbig2enc.exe out/bin/
          # Bundle common runtime DLLs to avoid PATH issues
          cp -v /c/msys64/mingw64/bin/lept*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/libpng*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/libjpeg*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/libtiff*.dll out/bin/ || true
          cp -v /c/msys64/mingw64/bin/zlib*.dll out/bin/ || true
          # Dev files if present
          if [ -d install_jb2/include ]; then cp -rv install_jb2/include/* out/include/; fi
          if ls install_jb2/lib/* 1>/dev/null 2>&1; then cp -v install_jb2/lib/* out/lib/; fi
        # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-0.30-Windows
          path: out/**
