  - name: Build jbig2enc 0.30
    shell: msys2 {0}
    run: |
      set -ex
      ZPREFIX="$PWD/install_zlib"

      # 编译/链接参数：用绝对路径的导入库，避免 -lz 探测误判；并带上 -lws2_32
      export ZLIB_CFLAGS="-I$ZPREFIX/include"
      export ZLIB_LIBS="$ZPREFIX/lib/libz.dll.a -lws2_32"
      export CPPFLAGS="$ZLIB_CFLAGS ${CPPFLAGS-}"
      export LDFLAGS="$ZLIB_LIBS ${LDFLAGS-}"
      export LIBS="$ZLIB_LIBS ${LIBS-}"

      # 通过 CONFIG_SITE 告诉 autoconf：头文件/链接都存在（尽管它后面还有自定义检测）
      cat > cache.site <<'EOF'
      ac_cv_header_zlib_h=yes
      ac_cv_lib_z_deflate=yes
      EOF
      export CONFIG_SITE="$PWD/cache.site"

      git clone --depth 1 --branch 0.30 https://github.com/agl/jbig2enc.git
      cd jbig2enc
      ./autogen.sh

      # ⚠️ 关键补丁：把“Error! zlib not detected.” 这类硬错误改成 no-op
      # （不同 autoconf 版本展开可能不同，下面两条都打一下，命中其一即可）
      sed -i 's/AC_MSG_ERROR(\[Error! zlib not detected\.\])/: # patched: skip zlib fatal/g' configure || true
      sed -i 's/echo "Error! zlib not detected\." ; exit 1/: # patched: skip zlib fatal/g' configure || true

      # 现在再跑 configure（若仍失败，导出 config.log 以便排障）
      ./configure --prefix="$PWD/../install_jb2" || { echo "=== tail config.log ==="; tail -n 200 config.log || true; exit 1; }

      make -j
      make install
